import { detectSession } from '../../shared/auth.js';
import { sfGet, sfPost, sfPatch, sanitizeId, escapeSoql } from '../../shared/api.js';
import { SF_API_VERSION, articleUrl } from '../../shared/config.js';

const KNOWLEDGE_ARTICLE_RT_ID = '012Hx00000002oEIAQ';
const CLAUDEGEN_MARKER = 'KBA-CLAUDEGEN';

function slugify(text) {
  return String(text || 'kb-draft')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 200);
}

function randomLetters(n) {
  const chars = 'abcdefghijklmnopqrstuvwxyz';
  let s = '';
  for (let i = 0; i < n; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return s;
}

function escapeHtml(str) {
  return String(str || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function buildClaudeGenStamp({ caseNumber, model } = {}) {
  const ts = new Date().toISOString();
  const caseFragment = caseNumber ? ` · Case ${escapeHtml(String(caseNumber))}` : '';
  const modelFragment = model ? ` · Model ${escapeHtml(String(model))}` : '';
  return [
    `<!-- ${CLAUDEGEN_MARKER} ${ts} -->`,
    `<p><strong>ClaudeGen</strong> — generated by KB Agent on ${ts}${caseFragment}${modelFragment}</p>`
  ].join('\n');
}

function sectionsToHtml(sections) {
  return (sections || []).map(s =>
    `<h2>${escapeHtml(s.heading || 'Section')}</h2>\n${markdownToHtml(s.body || '')}`
  ).join('\n');
}

function markdownToHtml(text) {
  const lines = String(text || '').split('\n');
  const output = [];
  let inList = null;
  for (const line of lines) {
    const isOl = /^\d+\.\s/.test(line);
    const isUl = line.startsWith('- ');
    if (isOl || isUl) {
      const listType = isOl ? 'ol' : 'ul';
      if (inList !== listType) {
        if (inList) output.push(`</${inList}>`);
        output.push(`<${listType}>`);
        inList = listType;
      }
      const content = isOl ? line.replace(/^\d+\.\s/, '') : line.slice(2);
      output.push(`<li>${escapeHtml(content)}</li>`);
    } else {
      if (inList) { output.push(`</${inList}>`); inList = null; }
      if (line.startsWith('## ')) output.push(`<h3>${escapeHtml(line.slice(3))}</h3>`);
      else if (line.startsWith('# ')) output.push(`<h2>${escapeHtml(line.slice(2))}</h2>`);
      else if (line.trim()) output.push(`<p>${escapeHtml(line)}</p>`);
    }
  }
  if (inList) output.push(`</${inList}>`);
  return output.join('\n');
}

const _ptLookupCache = new Map();

async function resolveProductAndTopic(apiBase, sid, { taxonomyName, taxonomyId }) {
  if (!taxonomyName && !taxonomyId) return { ok: false, reason: 'no-taxonomy' };

  const cacheKey = apiBase;
  let info = _ptLookupCache.get(cacheKey);
  if (info && Date.now() - info.ts > 5 * 60 * 1000) info = null;

  if (!info) {
    try {
      const desc = await sfGet(`${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav/describe`, sid);
      const fields = desc?.fields || [];
      const f = fields.find(x => String(x.name || '').toLowerCase() === 'product_and_topic__c');
      if (!f) return { ok: false, reason: 'field-not-found' };
      if (f.type !== 'reference' || !f.referenceTo?.length) return { ok: false, reason: 'not-a-lookup' };
      info = { ts: Date.now(), fieldName: f.name, refObject: f.referenceTo[0] };
      _ptLookupCache.set(cacheKey, info);
    } catch (e) {
      return { ok: false, reason: `describe-failed: ${e?.message}` };
    }
  }

  if (taxonomyId) {
    return { ok: true, fieldName: info.fieldName, idToWrite: taxonomyId };
  }

  const safeName = escapeSoql(taxonomyName);
  try {
    const q = `SELECT Id FROM ${info.refObject} WHERE Name = '${safeName}' LIMIT 1`;
    const data = await sfGet(`${apiBase}/services/data/${SF_API_VERSION}/query?q=${encodeURIComponent(q)}`, sid);
    const row = (data?.records || [])[0];
    if (!row?.Id) return { ok: false, reason: 'name-not-found' };
    return { ok: true, fieldName: info.fieldName, idToWrite: row.Id };
  } catch (e) {
    return { ok: false, reason: `query-failed: ${e?.message}` };
  }
}

export async function publishNewArticle(payload) {
  const session = await detectSession();
  if (!session.sid) return { success: false, error: 'No Salesforce session.' };
  const { apiBase, sid } = session;

  const record = {
    Title: payload.title || 'Untitled',
    UrlName: slugify(payload.title) + '-' + randomLetters(6),
    Summary: (payload.summary || '').slice(0, 1000),
    RecordTypeId: KNOWLEDGE_ARTICLE_RT_ID,
    Language: 'en_US'
  };

  const descriptionSections = (payload.sections || []).filter(s =>
    /description|problem|symptom|context|overview/i.test(s.heading)
  );
  const resolutionSections = (payload.sections || []).filter(s =>
    /resolution|solution|fix|steps|workaround/i.test(s.heading)
  );
  const otherSections = (payload.sections || []).filter(s =>
    !descriptionSections.includes(s) && !resolutionSections.includes(s)
  );

  record['Description__c'] = descriptionSections.length
    ? sectionsToHtml(descriptionSections)
    : sectionsToHtml(payload.sections?.slice(0, 1) || []);

  record['Resolution__c'] = resolutionSections.length
    ? sectionsToHtml(resolutionSections)
    : sectionsToHtml(otherSections);

  const stamp = buildClaudeGenStamp({ caseNumber: payload.caseNumber });
  record['Internal_Information__c'] = stamp;

  if (payload.taxonomyName || payload.taxonomyId) {
    const ptResult = await resolveProductAndTopic(apiBase, sid, {
      taxonomyName: payload.taxonomyName,
      taxonomyId: payload.taxonomyId
    });
    if (ptResult.ok) {
      record[ptResult.fieldName] = ptResult.idToWrite;
    }
  }

  try {
    const res = await sfPost(`${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav`, sid, record);
    const articleId = res?.id || res?.Id;
    if (!articleId) return { success: false, error: 'No ID returned from article creation.' };
    return {
      success: true,
      id: articleId,
      url: articleUrl(articleId)
    };
  } catch (e) {
    return { success: false, error: e?.message || 'Article creation failed.' };
  }
}

export async function publishUpdateDraft(payload) {
  const session = await detectSession();
  if (!session.sid) return { success: false, error: 'No Salesforce session.' };
  const { apiBase, sid } = session;

  const existingId = sanitizeId(payload.existingArticleId);

  let source;
  try {
    source = await sfGet(
      `${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav/${existingId}?fields=Id,Title,UrlName,RecordTypeId,KnowledgeArticleId,PublishStatus,Summary,Internal_Information__c`,
      sid
    );
  } catch (e) {
    return { success: false, error: `Could not fetch existing article: ${e?.message}` };
  }

  let masterArticleId;
  try {
    masterArticleId = sanitizeId(source.KnowledgeArticleId);
  } catch {
    return { success: false, error: 'Could not determine master article ID from the existing record.' };
  }

  const updates = buildArticleFields(payload, source);

  let ptWarning = null;
  if (payload.taxonomyName || payload.taxonomyId) {
    const ptResult = await resolveProductAndTopic(apiBase, sid, {
      taxonomyName: payload.taxonomyName,
      taxonomyId: payload.taxonomyId
    });
    if (ptResult.ok) updates[ptResult.fieldName] = ptResult.idToWrite;
    else ptWarning = `Product & Topic not applied (${ptResult.reason}).`;
  }

  // If the source is already a draft, patch it in place
  if (source.PublishStatus === 'Draft') {
    try {
      await sfPatch(
        `${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav/${existingId}`,
        sid,
        updates
      );
      return {
        success: true,
        id: existingId,
        url: articleUrl(existingId),
        masterArticleId,
        action: 'patched-draft',
        warning: ptWarning
      };
    } catch (e) {
      return { success: false, error: e?.message || 'Draft update failed.' };
    }
  }

  // Source is published — create a new draft version.
  // POST goes to the masterVersions COLLECTION (no ID in path); the article to
  // branch from is named by KnowledgeArticleId (kA0…) in the body. POSTing to
  // .../masterVersions/{id} is rejected with METHOD_NOT_ALLOWED.
  let newDraftId;
  try {
    const res = await sfPost(
      `${apiBase}/services/data/${SF_API_VERSION}/knowledgeManagement/articleVersions/masterVersions`,
      sid,
      { articleId: masterArticleId }
    );
    newDraftId = res?.id || res?.Id;
    if (!newDraftId) return { success: false, error: 'No draft ID returned from new-version creation.' };
  } catch (e) {
    return { success: false, error: `Could not create new draft version: ${e?.message}` };
  }

  // Patch the newly created draft with the updated content
  try {
    await sfPatch(
      `${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav/${newDraftId}`,
      sid,
      updates
    );
    return {
      success: true,
      id: newDraftId,
      url: articleUrl(newDraftId),
      masterArticleId,
      action: 'new-draft-version',
      warning: ptWarning
    };
  } catch (e) {
    return { success: false, error: `Draft version created (${newDraftId}) but content update failed: ${e?.message}` };
  }
}

function buildArticleFields(payload, source) {
  const record = {
    Title: payload.title || source.Title,
    Summary: (payload.summary || source.Summary || '').slice(0, 1000)
  };

  const descriptionSections = (payload.sections || []).filter(s =>
    /description|problem|symptom|context|overview/i.test(s.heading)
  );
  const resolutionSections = (payload.sections || []).filter(s =>
    /resolution|solution|fix|steps|workaround/i.test(s.heading)
  );
  const otherSections = (payload.sections || []).filter(s =>
    !descriptionSections.includes(s) && !resolutionSections.includes(s)
  );

  const descHtml = sectionsToHtml(descriptionSections) || sectionsToHtml(payload.sections?.slice(0, 1) || []);
  const resHtml = sectionsToHtml(resolutionSections) || sectionsToHtml(otherSections);

  // Only write body fields when we actually have content. Writing '' would blank
  // the existing Description/Resolution on a title- or summary-only edit (data loss).
  if (descHtml) record['Description__c'] = descHtml;
  if (resHtml) record['Resolution__c'] = resHtml;

  const stamp = buildClaudeGenStamp({ caseNumber: payload.caseNumber });
  const existingInfo = source.Internal_Information__c || '';
  record['Internal_Information__c'] = existingInfo
    ? `${existingInfo}\n<hr/>\n${stamp}`
    : stamp;

  return record;
}
