import { detectSession } from '../../shared/auth.js';
import { sfGet, sfPost, sfPatch, sanitizeId, escapeSoql } from '../../shared/api.js';
import { SF_API_VERSION, articleUrl } from '../../shared/config.js';
import { markdownToHtml, escapeHtml } from '../../shared/markdown.js';

const KNOWLEDGE_ARTICLE_RT_ID = '012Hx00000002oEIAQ';
const CLAUDEGEN_MARKER = 'KBA-CLAUDEGEN';

const TITLE_MAX = 255;
const SUMMARY_MAX = 1000;

function slugify(text) {
  return String(text || 'kb-draft')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 200);
}

function randomLetters(n) {
  const chars = 'abcdefghijklmnopqrstuvwxyz';
  let s = '';
  for (let i = 0; i < n; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return s;
}

function buildClaudeGenStamp({ caseNumber, model } = {}) {
  const ts = new Date().toISOString();
  const caseFragment = caseNumber ? ` · Case ${escapeHtml(String(caseNumber))}` : '';
  const modelFragment = model ? ` · Model ${escapeHtml(String(model))}` : '';
  return [
    `<!-- ${CLAUDEGEN_MARKER} ${ts} -->`,
    `<p><strong>ClaudeGen</strong> — generated by KB Agent on ${ts}${caseFragment}${modelFragment}</p>`
  ].join('\n');
}

function sectionsToHtml(sections) {
  return (sections || []).map(s =>
    `<h2>${escapeHtml(s.heading || 'Section')}</h2>\n${markdownToHtml(s.body || '', { headingBase: 3 })}`
  ).join('\n');
}

const DESC_HEADING_RE = /description|problem|symptom|context|overview/i;
const RES_HEADING_RE = /resolution|solution|fix|steps|workaround/i;

function buildBodyFields(sections) {
  const all = sections || [];
  const descriptionSections = all.filter(s => DESC_HEADING_RE.test(s.heading || ''));
  const resolutionSections = all.filter(s => RES_HEADING_RE.test(s.heading || ''));
  const otherSections = all.filter(s => !descriptionSections.includes(s) && !resolutionSections.includes(s));

  const descHtml = descriptionSections.length
    ? sectionsToHtml(descriptionSections)
    : sectionsToHtml(all.slice(0, 1));
  const resHtml = resolutionSections.length
    ? sectionsToHtml(resolutionSections)
    : sectionsToHtml(otherSections);

  return { descHtml, resHtml };
}

const _ptLookupCache = new Map();

async function resolveProductAndTopic(apiBase, sid, { taxonomyName, taxonomyId }) {
  if (!taxonomyName && !taxonomyId) return { ok: false, reason: 'no-taxonomy' };

  const cacheKey = apiBase;
  let info = _ptLookupCache.get(cacheKey);
  if (info && Date.now() - info.ts > 5 * 60 * 1000) info = null;

  if (!info) {
    try {
      const desc = await sfGet(`${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav/describe`, sid);
      const fields = desc?.fields || [];
      const f = fields.find(x => String(x.name || '').toLowerCase() === 'product_and_topic__c');
      if (!f) return { ok: false, reason: 'field-not-found' };
      if (f.type !== 'reference' || !f.referenceTo?.length) return { ok: false, reason: 'not-a-lookup' };
      info = { ts: Date.now(), fieldName: f.name, refObject: f.referenceTo[0] };
      _ptLookupCache.set(cacheKey, info);
    } catch (e) {
      return { ok: false, reason: `describe-failed: ${e?.message}` };
    }
  }

  if (taxonomyId) {
    return { ok: true, fieldName: info.fieldName, idToWrite: taxonomyId };
  }

  const safeName = escapeSoql(taxonomyName);
  try {
    const q = `SELECT Id FROM ${info.refObject} WHERE Name = '${safeName}' LIMIT 1`;
    const data = await sfGet(`${apiBase}/services/data/${SF_API_VERSION}/query?q=${encodeURIComponent(q)}`, sid);
    const row = (data?.records || [])[0];
    if (!row?.Id) return { ok: false, reason: 'name-not-found' };
    return { ok: true, fieldName: info.fieldName, idToWrite: row.Id };
  } catch (e) {
    return { ok: false, reason: `query-failed: ${e?.message}` };
  }
}

export async function publishNewArticle(payload) {
  const session = await detectSession();
  if (!session.sid) return { success: false, error: 'No Salesforce session.' };
  const { apiBase, sid } = session;

  const record = {
    Title: (payload.title || 'Untitled').slice(0, TITLE_MAX),
    UrlName: slugify(payload.title) + '-' + randomLetters(6),
    Summary: (payload.summary || '').slice(0, SUMMARY_MAX),
    RecordTypeId: KNOWLEDGE_ARTICLE_RT_ID,
    Language: 'en_US'
  };

  const { descHtml, resHtml } = buildBodyFields(payload.sections);
  record['Description__c'] = descHtml;
  record['Resolution__c'] = resHtml;

  const stamp = buildClaudeGenStamp({ caseNumber: payload.caseNumber });
  record['Internal_Information__c'] = stamp;

  if (payload.taxonomyName || payload.taxonomyId) {
    const ptResult = await resolveProductAndTopic(apiBase, sid, {
      taxonomyName: payload.taxonomyName,
      taxonomyId: payload.taxonomyId
    });
    if (ptResult.ok) {
      record[ptResult.fieldName] = ptResult.idToWrite;
    }
  }

  try {
    const res = await sfPost(`${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav`, sid, record);
    const articleId = res?.id || res?.Id;
    if (!articleId) return { success: false, error: 'No ID returned from article creation.' };
    return {
      success: true,
      id: articleId,
      url: articleUrl(articleId)
    };
  } catch (e) {
    return { success: false, error: e?.message || 'Article creation failed.' };
  }
}

export async function publishUpdateDraft(payload) {
  const session = await detectSession();
  if (!session.sid) return { success: false, error: 'No Salesforce session.' };
  const { apiBase, sid } = session;

  const existingId = sanitizeId(payload.existingArticleId);

  let source;
  try {
    source = await sfGet(
      `${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav/${existingId}?fields=Id,Title,UrlName,RecordTypeId,KnowledgeArticleId,PublishStatus,Summary,Internal_Information__c`,
      sid
    );
  } catch (e) {
    return { success: false, error: `Could not fetch existing article: ${e?.message}` };
  }

  let masterArticleId;
  try {
    masterArticleId = sanitizeId(source.KnowledgeArticleId);
  } catch {
    return { success: false, error: 'Could not determine master article ID from the existing record.' };
  }

  const updates = buildArticleFields(payload, source);

  if (source.PublishStatus === 'Draft') {
    const r = await patchArticleSavingContent(apiBase, sid, existingId, updates);
    if (!r.ok) return { success: false, error: r.error || 'Draft update failed.' };
    return {
      success: true,
      id: existingId,
      url: articleUrl(existingId),
      masterArticleId,
      action: 'patched-draft',
      warning: r.ptCleared ? STALE_PT_WARNING : null
    };
  }

  let newDraftId = await findExistingDraftId(apiBase, sid, masterArticleId);
  let reusedExistingDraft = !!newDraftId;

  if (!newDraftId) {
    try {
      const res = await sfPost(
        `${apiBase}/services/data/${SF_API_VERSION}/knowledgeManagement/articleVersions/masterVersions`,
        sid,
        { articleId: masterArticleId }
      );
      newDraftId = res?.id || res?.Id;
    } catch (e) {
      newDraftId = await findExistingDraftId(apiBase, sid, masterArticleId);
      if (!newDraftId) {
        return { success: false, error: `Could not create new draft version: ${e?.message}` };
      }
      reusedExistingDraft = true;
    }
  }
  if (!newDraftId) {
    newDraftId = await findExistingDraftId(apiBase, sid, masterArticleId);
    if (newDraftId) reusedExistingDraft = true;
  }
  if (!newDraftId) return { success: false, error: 'No draft ID returned from new-version creation.' };

  const r = await patchArticleSavingContent(apiBase, sid, newDraftId, updates);
  if (!r.ok) {
    return { success: false, error: `Draft version (${newDraftId}) ready but content update failed: ${r.error}` };
  }
  return {
    success: true,
    id: newDraftId,
    url: articleUrl(newDraftId),
    masterArticleId,
    action: reusedExistingDraft ? 'updated-existing-draft' : 'new-draft-version',
    warning: [
      reusedExistingDraft ? 'A draft already existed for this article; updated it instead of creating a new one.' : null,
      r.ptCleared ? STALE_PT_WARNING : null
    ].filter(Boolean).join(' ') || null
  };
}

const STALE_PT_WARNING = "The article's Product & Topic was stale (failed the org lookup filter) and was cleared so the rewrite could save. Re-tag the article's Product & Topic in Salesforce.";

async function patchArticleSavingContent(apiBase, sid, recordId, updates) {
  const url = `${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav/${recordId}`;
  try {
    await sfPatch(url, sid, updates);
    return { ok: true, ptCleared: false };
  } catch (e) {
    const msg = e?.message || '';
    const isStalePtFilter = /FIELD_FILTER_VALIDATION_EXCEPTION/i.test(msg) && /Product_And_Topic__c/i.test(msg);
    if (!isStalePtFilter) return { ok: false, error: msg || 'Update failed.' };

    try {
      await sfPatch(url, sid, { ...updates, Product_And_Topic__c: null });
      return { ok: true, ptCleared: true };
    } catch (e2) {
      return { ok: false, error: e2?.message || 'Update failed after clearing Product & Topic.' };
    }
  }
}

async function findExistingDraftId(apiBase, sid, masterArticleId) {
  try {
    const safeMaster = escapeSoql(masterArticleId);
    const q = `SELECT Id FROM Knowledge__kav WHERE KnowledgeArticleId = '${safeMaster}' AND PublishStatus = 'Draft' LIMIT 1`;
    const data = await sfGet(`${apiBase}/services/data/${SF_API_VERSION}/query?q=${encodeURIComponent(q)}`, sid);
    const row = (data?.records || [])[0];
    return row?.Id ? sanitizeId(row.Id) : null;
  } catch {
    return null;
  }
}

function buildArticleFields(payload, source) {
  const record = {
    Title: (payload.title || source.Title || '').slice(0, TITLE_MAX),
    Summary: (payload.summary || source.Summary || '').slice(0, SUMMARY_MAX)
  };

  const { descHtml, resHtml } = buildBodyFields(payload.sections);

  if (descHtml) record['Description__c'] = descHtml;
  if (resHtml) record['Resolution__c'] = resHtml;

  const stamp = buildClaudeGenStamp({ caseNumber: payload.caseNumber });
  const existingInfo = source.Internal_Information__c || '';
  record['Internal_Information__c'] = existingInfo
    ? `${existingInfo}\n<hr/>\n${stamp}`
    : stamp;

  return record;
}
