import { detectSession } from '../../shared/auth.js';
import { sfGet, sfPost, sanitizeId } from '../../shared/api.js';
import { SF_API_VERSION } from '../../shared/config.js';

const KNOWLEDGE_ARTICLE_RT_ID = '012Hx00000002oEIAQ';
const CLAUDEGEN_MARKER = 'KBA-CLAUDEGEN';

function slugify(text) {
  return String(text || 'kb-draft')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 200);
}

function randomLetters(n) {
  const chars = 'abcdefghijklmnopqrstuvwxyz';
  let s = '';
  for (let i = 0; i < n; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return s;
}

function escapeHtml(str) {
  return String(str || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function buildClaudeGenStamp({ caseNumber, model } = {}) {
  const ts = new Date().toISOString();
  const caseFragment = caseNumber ? ` · Case ${escapeHtml(String(caseNumber))}` : '';
  const modelFragment = model ? ` · Model ${escapeHtml(String(model))}` : '';
  return [
    `<!-- ${CLAUDEGEN_MARKER} ${ts} -->`,
    `<p><strong>ClaudeGen</strong> — generated by KB Agent on ${ts}${caseFragment}${modelFragment}</p>`
  ].join('\n');
}

function sectionsToHtml(sections) {
  return (sections || []).map(s =>
    `<h2>${escapeHtml(s.heading || 'Section')}</h2>\n${markdownToHtml(s.body || '')}`
  ).join('\n');
}

function markdownToHtml(text) {
  const lines = String(text || '').split('\n');
  const output = [];
  let inList = null;
  for (const line of lines) {
    const isOl = /^\d+\.\s/.test(line);
    const isUl = line.startsWith('- ');
    if (isOl || isUl) {
      const listType = isOl ? 'ol' : 'ul';
      if (inList !== listType) {
        if (inList) output.push(`</${inList}>`);
        output.push(`<${listType}>`);
        inList = listType;
      }
      const content = isOl ? line.replace(/^\d+\.\s/, '') : line.slice(2);
      output.push(`<li>${escapeHtml(content)}</li>`);
    } else {
      if (inList) { output.push(`</${inList}>`); inList = null; }
      if (line.startsWith('## ')) output.push(`<h3>${escapeHtml(line.slice(3))}</h3>`);
      else if (line.startsWith('# ')) output.push(`<h2>${escapeHtml(line.slice(2))}</h2>`);
      else if (line.trim()) output.push(`<p>${escapeHtml(line)}</p>`);
    }
  }
  if (inList) output.push(`</${inList}>`);
  return output.join('\n');
}

const _ptLookupCache = new Map();

async function resolveProductAndTopic(apiBase, sid, { taxonomyName, taxonomyId }) {
  if (!taxonomyName && !taxonomyId) return { ok: false, reason: 'no-taxonomy' };

  const cacheKey = apiBase;
  let info = _ptLookupCache.get(cacheKey);
  if (info && Date.now() - info.ts > 5 * 60 * 1000) info = null;

  if (!info) {
    try {
      const desc = await sfGet(`${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav/describe`, sid);
      const fields = desc?.fields || [];
      const f = fields.find(x => String(x.name || '').toLowerCase() === 'product_and_topic__c');
      if (!f) return { ok: false, reason: 'field-not-found' };
      if (f.type !== 'reference' || !f.referenceTo?.length) return { ok: false, reason: 'not-a-lookup' };
      info = { ts: Date.now(), fieldName: f.name, refObject: f.referenceTo[0] };
      _ptLookupCache.set(cacheKey, info);
    } catch (e) {
      return { ok: false, reason: `describe-failed: ${e?.message}` };
    }
  }

  if (taxonomyId) {
    return { ok: true, fieldName: info.fieldName, idToWrite: taxonomyId };
  }

  const safeName = String(taxonomyName).replace(/'/g, "\\'");
  try {
    const q = `SELECT Id FROM ${info.refObject} WHERE Name = '${safeName}' LIMIT 1`;
    const data = await sfGet(`${apiBase}/services/data/${SF_API_VERSION}/query?q=${encodeURIComponent(q)}`, sid);
    const row = (data?.records || [])[0];
    if (!row?.Id) return { ok: false, reason: 'name-not-found' };
    return { ok: true, fieldName: info.fieldName, idToWrite: row.Id };
  } catch (e) {
    return { ok: false, reason: `query-failed: ${e?.message}` };
  }
}

export async function publishNewArticle(payload) {
  const session = await detectSession();
  if (!session.sid) return { success: false, error: 'No Salesforce session.' };
  const { apiBase, sid } = session;

  const record = {
    Title: payload.title || 'Untitled',
    UrlName: slugify(payload.title) + '-' + randomLetters(6),
    Summary: (payload.summary || '').slice(0, 1000),
    RecordTypeId: KNOWLEDGE_ARTICLE_RT_ID,
    Language: 'en_US'
  };

  const descriptionSections = (payload.sections || []).filter(s =>
    /description|problem|symptom|context|overview/i.test(s.heading)
  );
  const resolutionSections = (payload.sections || []).filter(s =>
    /resolution|solution|fix|steps|workaround/i.test(s.heading)
  );
  const otherSections = (payload.sections || []).filter(s =>
    !descriptionSections.includes(s) && !resolutionSections.includes(s)
  );

  record['Description__c'] = descriptionSections.length
    ? sectionsToHtml(descriptionSections)
    : sectionsToHtml(payload.sections?.slice(0, 1) || []);

  record['Resolution__c'] = resolutionSections.length
    ? sectionsToHtml(resolutionSections)
    : sectionsToHtml(otherSections);

  const stamp = buildClaudeGenStamp({ caseNumber: payload.caseNumber });
  record['Internal_Information__c'] = stamp;

  if (payload.taxonomyName || payload.taxonomyId) {
    const ptResult = await resolveProductAndTopic(apiBase, sid, {
      taxonomyName: payload.taxonomyName,
      taxonomyId: payload.taxonomyId
    });
    if (ptResult.ok) {
      record[ptResult.fieldName] = ptResult.idToWrite;
    }
  }

  try {
    const res = await sfPost(`${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav`, sid, record);
    const articleId = res?.id || res?.Id;
    if (!articleId) return { success: false, error: 'No ID returned from article creation.' };
    return {
      success: true,
      id: articleId,
      url: `https://orgcs.lightning.force.com/lightning/r/Knowledge__kav/${articleId}/view`
    };
  } catch (e) {
    return { success: false, error: e?.message || 'Article creation failed.' };
  }
}

export async function publishUpdateDraft(payload) {
  const session = await detectSession();
  if (!session.sid) return { success: false, error: 'No Salesforce session.' };
  const { apiBase, sid } = session;

  const existingId = sanitizeId(payload.existingArticleId);

  let source;
  try {
    source = await sfGet(
      `${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav/${existingId}?fields=Id,Title,UrlName,RecordTypeId,KnowledgeArticleId,Summary,Internal_Information__c`,
      sid
    );
  } catch (e) {
    return { success: false, error: `Could not fetch existing article: ${e?.message}` };
  }

  const suffix = randomLetters(8);
  const draftUrlName = slugify(`${source.UrlName || source.Title || 'draft'}-update-${suffix}`);

  const record = {
    Title: payload.title || source.Title,
    UrlName: draftUrlName,
    Summary: (payload.summary || source.Summary || '').slice(0, 1000),
    RecordTypeId: source.RecordTypeId || KNOWLEDGE_ARTICLE_RT_ID,
    Language: 'en_US'
  };

  if (source.KnowledgeArticleId) {
    record.KnowledgeArticleId = source.KnowledgeArticleId;
  }

  record['Description__c'] = sectionsToHtml(
    (payload.sections || []).filter(s => /description|problem|symptom|context|overview/i.test(s.heading))
  ) || sectionsToHtml(payload.sections?.slice(0, 1) || []);

  record['Resolution__c'] = sectionsToHtml(
    (payload.sections || []).filter(s => /resolution|solution|fix|steps|workaround/i.test(s.heading))
  ) || sectionsToHtml((payload.sections || []).slice(1));

  const stamp = buildClaudeGenStamp({ caseNumber: payload.caseNumber });
  const existingInfo = source.Internal_Information__c || '';
  record['Internal_Information__c'] = existingInfo
    ? `${existingInfo}\n<hr/>\n${stamp}`
    : stamp;

  if (payload.taxonomyName || payload.taxonomyId) {
    const ptResult = await resolveProductAndTopic(apiBase, sid, {
      taxonomyName: payload.taxonomyName,
      taxonomyId: payload.taxonomyId
    });
    if (ptResult.ok) record[ptResult.fieldName] = ptResult.idToWrite;
  }

  try {
    const res = await sfPost(`${apiBase}/services/data/${SF_API_VERSION}/sobjects/Knowledge__kav`, sid, record);
    const articleId = res?.id || res?.Id;
    if (!articleId) return { success: false, error: 'No ID returned.' };
    return {
      success: true,
      id: articleId,
      url: `https://orgcs.lightning.force.com/lightning/r/Knowledge__kav/${articleId}/view`,
      masterArticleId: source.KnowledgeArticleId || null
    };
  } catch (e) {
    return { success: false, error: e?.message || 'Draft creation failed.' };
  }
}
